export const siteData = {
    features: {
        enableFloatingWA: true,
        waRotator: true,
        enableAnimations: true,
        enableSEOJSONLD: true,
        enablePromoBar: true,
    },
    general: {
        brandName: "Dapur Berkah Catering",
        logo: "/logo-dapur.png",
        whatsappNumbers: [
            "6281234567890",
            "6289876543210",
        ],
        whatsappMessage: "Halo, saya ingin bertanya tentang layanan catering.",
    },
    social: {
        facebook: "https://facebook.com/dapurberkahcatering",
        instagram: "https://instagram.com/dapurberkahcatering",
        twitter: "https://twitter.com/dapurberkah",
        youtube: "https://youtube.com/@dapurberkahcatering",
    },
    navbar: {
        links: [
            { label: "Layanan", href: "#layanan" },
            { label: "Menu", href: "/menu" },
            { label: "Testimoni", href: "#testimoni" },
        ],
    },
    hero: {
        headline: "CATERING BERKAH",
        subheadline: "Hidangan lezat untuk setiap momen spesial Anda. Dari acara pernikahan hingga meeting kantor.",
        ctaText: "Pesan Sekarang",
        image: "/tumpeng-nobg.png",
    },
    promoBar: {
        message: "🎉 Promo Spesial: Diskon 15% untuk Pemesanan Paket Pernikahan! Berlaku hingga akhir bulan.",
        linkText: "Hubungi Kami",
        linkUrl: "#kontak",
        backgroundColor: "bg-orange-600",
    },
    categories: [
        { iconName: "Utensils", label: "Prasmanan", slug: "prasmanan" },
        { iconName: "Box", label: "Nasi Box", slug: "nasi-box" },
        { iconName: "Coffee", label: "Snack Box", slug: "snack-box" },
        { iconName: "ChefHat", label: "Tumpeng", slug: "tumpeng" },
        { iconName: "Truck", label: "Delivery", slug: "delivery" },
        { iconName: "Star", label: "Premium", slug: "premium" },
    ],
    featuredProducts: [
        {
            title: "Paket Prasmanan Lengkap",
            price: 85000,
            discountPrice: 100000,
            image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=1000&auto=format&fit=crop",
            badge: "Best Seller",
            category: "prasmanan",
            description: "Paket prasmanan lengkap untuk 50-100 orang dengan berbagai pilihan menu.",
        },
        {
            title: "Nasi Box Premium",
            price: 35000,
            image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=1000&auto=format&fit=crop",
            badge: "Populer",
            category: "nasi-box",
            description: "Nasi box dengan lauk premium dan kemasan eksklusif.",
        },
        {
            title: "Snack Box Meeting",
            price: 25000,
            image: "https://images.unsplash.com/photo-1558961363-fa8fdf82db35?q=80&w=1000&auto=format&fit=crop",
            badge: "Hemat",
            category: "snack-box",
            description: "Snack box 3 macam untuk meeting dan acara kantor.",
        },
        {
            title: "Tumpeng Nusantara",
            price: 450000,
            image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?q=80&w=1000&auto=format&fit=crop",
            badge: "Spesial",
            category: "tumpeng",
            description: "Tumpeng lengkap dengan lauk pauk tradisional untuk acara spesial.",
        },
        {
            title: "Paket Prasmanan Ekonomis",
            price: 65000,
            image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?q=80&w=1000&auto=format&fit=crop",
            badge: "Hemat",
            category: "prasmanan",
            description: "Paket prasmanan hemat dengan menu pilihan.",
        },
        {
            title: "Nasi Box Ayam Geprek",
            price: 28000,
            image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?q=80&w=1000&auto=format&fit=crop",
            badge: "Favorit",
            category: "nasi-box",
            description: "Nasi box dengan ayam geprek sambal level pilihan.",
        },
        {
            title: "Snack Box Premium",
            price: 35000,
            image: "https://images.unsplash.com/photo-1587241321091-ee6f68ac4dce?q=80&w=1000&auto=format&fit=crop",
            badge: "Premium",
            category: "snack-box",
            description: "Snack box 5 macam dengan kue kering premium.",
        },
        {
            title: "Tumpeng Mini",
            price: 250000,
            image: "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?q=80&w=1000&auto=format&fit=crop",
            badge: "Mini",
            category: "tumpeng",
            description: "Tumpeng mini untuk acara ulang tahun dan syukuran.",
        },
    ],
    testimonials: [
        {
            name: "Ibu Sari",
            review: "Catering untuk acara pernikahan anak saya sangat memuaskan. Rasa makanan enak dan penyajiannya rapi!",
            rating: 5,
        },
        {
            name: "Pak Budi",
            review: "Sudah 3 tahun langganan untuk meeting kantor. Selalu tepat waktu dan kualitas terjaga.",
            rating: 5,
        },
        {
            name: "Ibu Ratna",
            review: "Snack box nya enak-enak dan porsinya pas. Cocok untuk acara arisan dan pengajian.",
            rating: 5,
        },
    ],
    footer: {
        description: "Layanan catering terpercaya untuk berbagai acara. Kualitas terjamin, rasa istimewa.",
        quickLinks: [
            { label: "Tentang Kami", href: "#" },
            { label: "Cara Pemesanan", href: "#" },
            { label: "Syarat & Ketentuan", href: "#" },
            { label: "Kebijakan Privasi", href: "#" },
        ],
    },
};